apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/phoban01/flux-mt-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 1m0s
  path: ./tenants/team-a
  prune: true
  serviceAccountName: team-a
  validation: client
  sourceRef:
    kind: GitRepository
    name: team-a

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-a
  name: team-a

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-a
  name: team-a
  namespace: team-a

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-a
  name: team-a-reconciler
  namespace: team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:team-a:reconciler
- kind: ServiceAccount
  name: team-a
  namespace: team-a

